language: node_js
dist: trusty
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install -g gitbook-cli
  - npm install -g gitbook-pdf

script:
  - gitbook install
  - gitbook build
  - echo "Removing unwanted files"
  - rm -vf _book/.travis.yml
  - rm -vf _book/*.yml
  - rm -vf _book/*.md
  - rm -vf _book/*.sh
  - echo "Generating PDF for downloading"
  - gitbook pdf .

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _book
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    github_token: $GITHUB_TOKEN 
    file_glob: true
    file: $BUILD_NAME.*
    skip_cleanup: true
    on:
      tags: false
      branch: master

branches:
  only:
    - master
